const Erros = {
    DESCONHECIDO: "DESCONHECIDO",
    EMAIL_INVALIDO: "EMAIL_INVALIDO",
    NOME_PEQUENO: "NOME_PEQUENO",
    ID_INVALIDO: "ID_INVALIDO",
    NOME_VAZIO: "NOME_VAZIO",
    NOME_GRANDE: "NOME_GRANDE",
    NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
    NOME_CARACTERES_ESPECIAIS: "NOME_CARACTERES_ESPECIAIS",
    SENHA_FRACA: "SENHA_FRACA",
    SENHA_HASH_INVALIDA: "SENHA_HASH_INVALIDA",
    DURACAO_NEGATIVA: "DURACAO_NEGATIVA",
    URL_INVALIDA: "URL_INVALIDA",
    ORDEM_INVALIDA: "ORDEM_INVALIDA",
    AULA_DURACAO_ZERADA: "AULA_DURACAO_ZERADA",
} as const

export default Erros